{
    "code":"A123",
    "scode":"S223",
    "title":"mark industry",
    "email":"firdouserp@hotmail.com",
    "contact":"033315752320",
    "address":"asfafdagadsfgda",
    "cnic":"42201544245200",
    "businesstitle" : "marka industry",
    "nature" : "steels",
    "active" : "active",
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNSIsImlhdCI6MTYwODM3MTAzMywiZXhwIjoxNjA4NDU3NDMzfQ.Bfeo-ZbCMy8Hwyhtfoo34YBQiELiFGdW4DZRa19cYOI"

}